// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsdisfhrgxatxaenyrbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zZGlzZmhyZ3hhdHhhZW55cmJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgyNDYxMTcsImV4cCI6MjA4MzgyMjExN30.SnpqPJIa2yEeRVj92e2mDqC3Nryhem9x7SqL6iye2e0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});